name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit (ruff, mypy, basic checks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # setuptools-scm needs git history

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          environments: default
          locked: true

      - name: Run pre-commit
        run: pixi run pre-commit run --all-files --show-diff-on-failure

  tests:
    name: Tests (${{ matrix.environment }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Lowest and most recent supported Python version, and with xcube
        # and ESMValCore.
        environment: [py311, py314, xcube, esmvalcore]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          environments: ${{ matrix.environment }}
          locked: true

      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: coverage.xml
          flags: ${{ matrix.environment }}
          token: ${{ secrets.CODECOV_TOKEN }}
